### ISSUE TITLE
`List.to_seq`/`List.of_seq` missing

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [c-cube/seq#11]
While not strictly the `Seq` module, OCaml 4.07 also introduced `List.to_seq` and `List.of_seq` and it might be nice to have implementations of those as well, so `Seq` code is more "drop-in" compatible.

**Comment by gasche** [comment]
It's tricky to implement a `List` module within `seq`, in a way that is compatible with the code of people not using the compatibility module. (This is something that Stdcompat can do, because it's based on the idea that you explicitly `open StdCompat` and don't say anything else about it, but I don't think it would fit with `seq`'s more minimal design.)

**Comment by c-cube** [comment]
Honestly, this is a compatibility module _for the type_, not the rest. If you want a more comprehensive API, I have at least [oseq](https://github.com/c-cube/oseq/) and [CCSeq in containers](https://c-cube.github.io/ocaml-containers/3.6/containers/CCSeq/index.html) for that. You can cherry pick functions from either one if you want :)

**Comment by Leonidas-from-XIV** [comment]
That's alright, I was mostly curious how much `Seq` this project would support. I therefore assume the idea is to keep it at the state of the `Seq` module how it was introduced in 4.07, without the additions from 4.11 and 4.13?

**Comment by c-cube** [comment]
Pretty much, I think :-). The idea is that you drop `seq` as a dependency when your minimum OCaml value reaches 4.07 (and above that it's already a no-op).
